steps:

  # Paso 1: Construir la aplicación Spring Boot con Maven
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']

  # Paso 2: Construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA', '.']

  # Paso 3: Hacer push de la imagen de Docker a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA']

  # Paso 4: Desplegar a Cloud Run
  - name: 'gcr.io/google-cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_IMAGE_NAME-$SHORT_SHA'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA'
      - '--region'
      - 'us-central'

options:
  logging: CLOUD_LOGGING_ONLY