steps:

  # Construir la aplicación Spring Boot con Maven
  - name: 'maven:3.9-eclipse-temurin-21-alpine'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']

  # Construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA', '.']

  # Hacer push de la imagen de Docker a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA']

options:
  logging: CLOUD_LOGGING_ONLY
