application:

  security:
    jwt:
      secret-key: VUZTys5QdyfGP4iRe4TIe8o4k2YsSYk7j7j9liqce26grAmyS7
      expiration: 21600000


spring:

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/supermercados_globales
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "0000"

  jpa:
    show-sql: true
  #   hibernate:
  #     ddl-auto: update


management:

  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  show-actuator: true
