application:

  security:
    jwt:
      secret-key: ${JWT_SERCRET_KEY}
      expiration: ${JWT_EXPIRATION}


spring:

  datasource:
    url: jdbc:mysql://34.168.212.133:3306/supermercados_globales
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
