application:

  security:
    jwt:
      secret-key: ${JWT_SERCRET_KEY}
      expiration: ${JWT_EXPIRATION}


spring:

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
